
---

instance_groups:
  - name: concourse
    jobs:
      - name: web
        properties:
          main_team:
            auth:
              github:
                users:
                  - (( append ))
                  - schmie
                  - venusbb
