---

- type: replace
  path: /releases/-
  value:
    name: ipsec
    version: 0.1.4
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/ipsec-0.1.4.tgz
    sha1: 37358e942d1507d31d2080e94ba376510fc8ce76

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    name: racoon
    release: ipsec
    properties:
      racoon:
        ports:
        - name: router
          targets: ((terraform_outputs_cell_subnet_cidr_blocks))
        certificate_authority_private_key: "((ipsec_ca.private_key))"
        certificate_authority_cert: "((ipsec_ca.certificate))"
        level: use
        verify_certificate: 'on'

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: racoon
    release: ipsec
    properties:
      racoon:
        ports:
        - name: cell
          targets: ((terraform_outputs_router_subnet_cidr_blocks))
        certificate_authority_private_key: "((ipsec_ca.private_key))"
        certificate_authority_cert: "((ipsec_ca.certificate))"
        level: use
        verify_certificate: 'on'
