---
- type: remove
  path: /instance_groups/name=bosh/properties/director/default_ssh_options
- type: remove
  path: /instance_groups/name=bosh/properties/director/enable_nats_delivered_templates
- type: remove
  path: /instance_groups/name=bosh/properties/director/generate_vm_passwords
- type: replace
  path: /instance_groups/name=bosh/properties/director/disks?/max_orphaned_age_in_days
  value: 0
